version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console:
        class: rich.logging.RichHandler
        level: DEBUG
        formatter: simple
        rich_tracebacks: true  # enable rich tracebacks in console  file:
    
    file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: myapp.log
        mode: a
loggers:
    development:
        level: DEBUG
        handlers: [file, console]
        propagate: no
    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    production:
        level: WARNING
        handlers: [file]
        propagate: no
root:
    level: DEBUG
    handlers: [console]
